[theme]
# DDS system tokens → reference hex
primaryColor = "#543FDE"             # purple500
backgroundColor = "#FFFFFF"          # neutralLight50
secondaryBackgroundColor = "#FAFAFA" # neutralLight100
textColor = "#2E2E38"                # neutralDark700
font = "sans serif"
