[[pages]]
path = "home_page.py"
name = "Home"

[[pages]]
path = "interest_rate_page.py"
name = "Overnight Rates"

[[pages]]
path = "rate_curves_page.py"
name = "Rate Curves"

[[pages]]
path = "liability_overview_page.py"
name = "Liability Overview"

